#!/bin/bash

chmod u+x Savegit_linux

git init
git remote add origin https://github.com/kbijker/Linux-wannehaves.git
git add *
git status

echo -n "Geef commentaar:"
read -r
comm=$REPLY
git commit -m "$comm"

git branch -M main
git push -u origin main

git status

